import {
    BarChart3,
    Boxes,
    Inbox,
    LayoutDashboard,
    Package,
    QrCode,
    ShoppingBag,
} from 'lucide-react';
import type { CooperativeNavItem } from '@/types/cooperative-navigation';

export const COOPERATIVE_NAV_ITEMS: CooperativeNavItem[] = [
    {
        key: 'overview',
        label: 'Overview',
        href: '/cooperative',
        icon: LayoutDashboard,
        status: 'active',
        description: 'Ringkasan operasional dan modul kerja koperasi',
    },
    {
        key: 'orders',
        label: 'Pesanan',
        href: '/cooperative/orders',
        icon: ShoppingBag,
        status: 'active',
        badge: 'Aktif',
        description: 'Manajemen antrean pesanan & status pemenuhan',
    },
    {
        key: 'consignments',
        label: 'Titipan Siswa',
        href: '/cooperative/consignments',
        icon: Inbox,
        status: 'active',
        badge: 'Aktif',
        description: 'Kurasi & persetujuan produk konsinyasi siswa',
    },
    {
        key: 'products',
        label: 'Produk',
        href: '/cooperative/products',
        icon: Package,
        status: 'active',
        badge: 'Aktif',
        description: 'Katalog produk koperasi & kontrol harga',
    },
    {
        key: 'inventory',
        label: 'Stok',
        href: '/cooperative/inventory',
        icon: Boxes,
        status: 'active',
        badge: 'Aktif',
        description: 'Mutasi inventaris & opname stok fisik',
    },
    {
        key: 'pickup',
        label: 'Pickup',
        href: '/cooperative/pickup',
        icon: QrCode,
        status: 'active',
        badge: 'Aktif',
        description: 'Verifikasi pemindai QR loket pengambilan',
    },
    {
        key: 'reports',
        label: 'Laporan',
        href: '/cooperative/reports',
        icon: BarChart3,
        status: 'upcoming',
        badge: 'Segera',
        description: 'Rekapitulasi penjualan & pembukuan koperasi',
    },
];
